version: 2.1

jobs:
  test:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      # Replace this with the actual test commands for your project
      - run:
          name: Run tests
          command: echo 'replace me with real tests!' && false

  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      # Replace this with steps to build your project
      - run:
          name: Build the project
          command: # Add your build commands here

  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      # Replace this with steps to deploy your project
      - run:
          name: Deploy the project
          command: # Add your deploy commands here

workflows:
  example:
    jobs:
      - test
      - build:
          requires:
            - test
      - deploy:
          requires:
            - build